package cn.ibizlab.ai.logic.ai_agent_memory_tasklogic.fill_default_doc_id;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_memory_task ai_agent_memory_taskfill_default_doc_iddefault;
        global cn.ibizlab.core.ai.service.Iai_agent_memory_taskService iBzSysAi_agent_memory_taskDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_memory_taskfill_default_doc_idbegin"
            when
            then
            end

            //逻辑处理节点[根据类型填充文档标识]
            rule "rawsfcode_01"
            ruleflow-group "ai_agent_memory_taskfill_default_doc_idrawsfcode_01"
            when
            then
                        update(ai_agent_memory_taskfill_default_doc_iddefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_memory_taskfill_default_doc_idend_01"
            when
            then
                        update(ai_agent_memory_taskfill_default_doc_iddefault);//更新fact中变量值
            end