package cn.ibizlab.ai.logic.ai_agent_memory_tasklogic.get_document;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_memory_task ai_agent_memory_taskget_documentdefault;
        global cn.ibizlab.core.ai.service.Iai_agent_memory_taskService iBzSysAi_agent_memory_taskDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_memory_taskget_documentbegin"
            when
            then
            end

            //逻辑处理节点[获取记忆文档，不存在则建立]
            rule "rawsfcode_01"
            ruleflow-group "ai_agent_memory_taskget_documentrawsfcode_01"
            when
            then
                        update(ai_agent_memory_taskget_documentdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_memory_taskget_documentend_01"
            when
            then
                        update(ai_agent_memory_taskget_documentdefault);//更新fact中变量值
            end