package cn.ibizlab.ai.logic.ai_agent_memory_tasklogic.save_chunk;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_memory_task ai_agent_memory_tasksave_chunkdefault;
                global java.util.Map ai_agent_memory_tasksave_chunkchunk;
        global cn.ibizlab.core.ai.service.Iai_agent_memory_taskService iBzSysAi_agent_memory_taskDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_memory_tasksave_chunkbegin"
            when
            then
            end

            //逻辑处理节点[保存记忆分块]
            rule "rawsfcode_01"
            ruleflow-group "ai_agent_memory_tasksave_chunkrawsfcode_01"
            when
            then
                        update(ai_agent_memory_tasksave_chunkdefault);//更新fact中变量值
                        update(ai_agent_memory_tasksave_chunkchunk);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_memory_tasksave_chunkend_01"
            when
            then
                        update(ai_agent_memory_tasksave_chunkdefault);//更新fact中变量值
                        update(ai_agent_memory_tasksave_chunkchunk);//更新fact中变量值
            end