package cn.ibizlab.base.logic.userlogic.report_flag_filter;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.user userreport_flag_filterdefault;
                global cn.ibizlab.core.base.domain.user userreport_flag_filteruser_filter;
                global cn.ibizlab.core.base.domain.user userreport_flag_filteruser_page;
        global cn.ibizlab.core.base.service.IuserService iBzSysUserDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "userreport_flag_filterbegin"
            when
            then
            end