package cn.ibizlab.ai.logic.ai_modellogic.get_cloud_config;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_model ai_modelget_cloud_configdefault;
                global java.util.Map ai_modelget_cloud_configmap;
        global cn.ibizlab.core.ai.service.Iai_modelService iBzSysAi_modelDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_modelget_cloud_configbegin"
            when
            then
            end

            //逻辑处理节点[计算配置]
            rule "rawsfcode_01"
            ruleflow-group "ai_modelget_cloud_configrawsfcode_01"
            when
            then
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_modelget_cloud_configend_01"
            when
            then
                        update(ai_modelget_cloud_configdefault);//更新fact中变量值
                        update(ai_modelget_cloud_configmap);//更新fact中变量值
            end