package cn.ibizlab.ai.logic.ai_model_providerlogic.create_ai_credential;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_model_provider ai_model_providercreate_ai_credentialdefault;
                global cn.ibizlab.core.ai.domain.ai_credential ai_model_providercreate_ai_credentialcredential;
                global cn.ibizlab.core.ai.domain.ai_credential ai_model_providercreate_ai_credentialcredential_filter;
                global cn.ibizlab.core.ai.domain.ai_credential ai_model_providercreate_ai_credentialcredentials;
                    global cn.ibizlab.core.ai.service.Iai_credentialService ai_credentialservice;
        global cn.ibizlab.core.ai.service.Iai_model_providerService iBzSysAi_model_providerDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_model_providercreate_ai_credentialbegin"
            when
            then
            end

            //逻辑处理节点[提供商是否已存在]
            rule "dedataset_01"
            ruleflow-group "ai_model_providercreate_ai_credentialdedataset_01"
            when
            then
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[获取凭证]
            rule "deaction_03"
            ruleflow-group "ai_model_providercreate_ai_credentialdeaction_03"
            when
            then
                            cn.ibizlab.util.helper.CachedBeanCopier.copy(ai_credentialservice.get(ai_model_providercreate_ai_credentialcredential.getId()),ai_model_providercreate_ai_credentialcredential);
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "ai_model_providercreate_ai_credentialprepareparam_02"
            when
            then
                            ai_model_providercreate_ai_credentialcredential.set("name",ai_model_providercreate_ai_credentialdefault.get("name"));
                            ai_model_providercreate_ai_credentialcredential.set("bearertoken",ai_model_providercreate_ai_credentialdefault.get("defaulttoken"));
                            ai_model_providercreate_ai_credentialcredential.set("credentialtype","bearer_token");
                            ai_model_providercreate_ai_credentialcredential.set("provider",ai_model_providercreate_ai_credentialdefault.get("id"));
                            ai_model_providercreate_ai_credentialcredential.set("codename",ai_model_providercreate_ai_credentialdefault.get("id"));
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_03"
            ruleflow-group "ai_model_providercreate_ai_credentialprepareparam_03"
            when
            then
                            ai_model_providercreate_ai_credentialcredential.set("bearertoken",ai_model_providercreate_ai_credentialdefault.get("defaulttoken"));
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[删除凭证信息]
            rule "deaction_04"
            ruleflow-group "ai_model_providercreate_ai_credentialdeaction_04"
            when
            then
                        ai_credentialservice.remove(ai_model_providercreate_ai_credentialcredential.getId());
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[创建凭证]
            rule "deaction_01"
            ruleflow-group "ai_model_providercreate_ai_credentialdeaction_01"
            when
            then
                        ai_credentialservice.create(ai_model_providercreate_ai_credentialcredential);
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[更新凭证]
            rule "deaction_02"
            ruleflow-group "ai_model_providercreate_ai_credentialdeaction_02"
            when
            then
                        ai_credentialservice.update(ai_model_providercreate_ai_credentialcredential);
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_model_providercreate_ai_credentialend_01"
            when
            then
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_model_providercreate_ai_credentialprepareparam_01"
            when
            then
                            ai_model_providercreate_ai_credentialcredential_filter.set("n_id_eq",ai_model_providercreate_ai_credentialdefault.get("id"));
                            ai_model_providercreate_ai_credentialcredential.set("id",ai_model_providercreate_ai_credentialdefault.get("id"));
                        update(ai_model_providercreate_ai_credentialdefault);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredential_filter);//更新fact中变量值
                        update(ai_model_providercreate_ai_credentialcredentials);//更新fact中变量值
            end