package cn.ibizlab.wiki.logic.spacelogic.createcorrespondingkb;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.wiki.domain.space spacecreatecorrespondingkbdefault;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base spacecreatecorrespondingkbai_knowledge_base;
                    global cn.ibizlab.core.ai.service.Iai_knowledge_baseService ai_knowledge_baseservice;
        global cn.ibizlab.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacecreatecorrespondingkbbegin"
            when
            then
            end

            //逻辑处理节点[设置知识库数据]
            rule "prepareparam_01"
            ruleflow-group "spacecreatecorrespondingkbprepareparam_01"
            when
            then
                            spacecreatecorrespondingkbai_knowledge_base.set("id",spacecreatecorrespondingkbdefault.get("id"));
                            spacecreatecorrespondingkbai_knowledge_base.set("name",spacecreatecorrespondingkbdefault.get("name"));
                            spacecreatecorrespondingkbai_knowledge_base.set("visibility",spacecreatecorrespondingkbdefault.get("visibility"));
                            spacecreatecorrespondingkbai_knowledge_base.set("parserconfig","{"auto_keywords":4,"auto_questions":5,"chunk_token_num":512,"delimiter":"\n","layout_recognize":"DeepDOC","task_page_size":12,"raptor":{"use_raptor":1,"max_token":"256","threshold":"0.1","max_cluster":"64","random_seed":"42","prompt":"请总结以下段落。 小心数字，不要编造。 段落如下：       {cluster_content} 以上就是你需要总结的内容。"},"graphrag":{"use_graphrag":1,"resolution":"1","entity_types":"organization,time,event,person,geo,product","method":"general"},"chunk_overlap":123,"chunk_overlap_num":30,"chunk_size":52,"keep_separator":1,"max_chunk_count_per_doc":111,"separator":"-","data_masking_rules":[{}],"method":"FIXED"}");
                            spacecreatecorrespondingkbai_knowledge_base.set("chunkmethod","FIXED");
                        update(spacecreatecorrespondingkbdefault);//更新fact中变量值
                        update(spacecreatecorrespondingkbai_knowledge_base);//更新fact中变量值
            end

            //逻辑处理节点[创建知识库]
            rule "deaction_01"
            ruleflow-group "spacecreatecorrespondingkbdeaction_01"
            when
            then
                        ai_knowledge_baseservice.create(spacecreatecorrespondingkbai_knowledge_base);
                        update(spacecreatecorrespondingkbdefault);//更新fact中变量值
                        update(spacecreatecorrespondingkbai_knowledge_base);//更新fact中变量值
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_02"
            ruleflow-group "spacecreatecorrespondingkbprepareparam_02"
            when
            then
                        update(spacecreatecorrespondingkbdefault);//更新fact中变量值
                        update(spacecreatecorrespondingkbai_knowledge_base);//更新fact中变量值
            end