package cn.ibizlab.wiki.logic.spacelogic.del_relation;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.wiki.domain.space spacedel_relationdefault;
        global cn.ibizlab.core.wiki.service.IspaceService iBzSysSpaceDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "spacedel_relationbegin"
            when
            then
            end