package cn.ibizlab.base.logic.role_memberlogic.currole;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.role_member role_membercurroledefault;
                global java.util.Map role_membercurrolefilteredroles;
        global cn.ibizlab.core.base.service.Irole_memberService iBzSysRole_memberDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "role_membercurrolebegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "role_membercurrolerawsfcode_01"
            when
            then
                        update(role_membercurroledefault);//更新fact中变量值
                        update(role_membercurrolefilteredroles);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "role_membercurroleend_01"
            when
            then
                        update(role_membercurroledefault);//更新fact中变量值
                        update(role_membercurrolefilteredroles);//更新fact中变量值
            end