package cn.ibizlab.ai.logic.ai_agent_contextlogic.beforefile;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextbeforefiledefault;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextbeforefilebegin"
            when
            then
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "ai_agent_contextbeforefiledebugparam_01"
            when
            then
                        update(ai_agent_contextbeforefiledefault);//更新fact中变量值
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall_01"
            ruleflow-group "ai_agent_contextbeforefilerawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_agent_contextbeforefiledefault.get("template_id"));
    String strSql="select id as ai_agent_id from ai_agent where id = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysAi_agent_contextDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ai_agent_contextbeforefiledefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ai_agent_contextbeforefiledefault);//更新fact中变量值
            end