package cn.ibizlab.ai.logic.ai_agent_contextlogic.bind;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextbinddefault;
                global cn.ibizlab.core.ai.domain.ai_agent_assignment ai_agent_contextbindai_agent_assignment;
                    global cn.ibizlab.core.ai.service.Iai_agent_assignmentService ai_agent_assignmentservice;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextbindbegin"
            when
            then
            end

            //逻辑处理节点[准备绑定智能体参数]
            rule "prepareparam_01"
            ruleflow-group "ai_agent_contextbindprepareparam_01"
            when
            then
                            ai_agent_contextbindai_agent_assignment.set("contextid",ai_agent_contextbinddefault.get("id"));
                            ai_agent_contextbindai_agent_assignment.set("usetag",ai_agent_contextbinddefault.get("use_tag"));
                        update(ai_agent_contextbinddefault);//更新fact中变量值
                        update(ai_agent_contextbindai_agent_assignment);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "ai_agent_contextbinddebugparam_01"
            when
            then
                        update(ai_agent_contextbinddefault);//更新fact中变量值
                        update(ai_agent_contextbindai_agent_assignment);//更新fact中变量值
            end

            //逻辑处理节点[绑定智能体]
            rule "deaction_01"
            ruleflow-group "ai_agent_contextbinddeaction_01"
            when
            then
                        ai_agent_assignmentservice.create(ai_agent_contextbindai_agent_assignment);
                        update(ai_agent_contextbinddefault);//更新fact中变量值
                        update(ai_agent_contextbindai_agent_assignment);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_contextbindend_01"
            when
            then
                        update(ai_agent_contextbinddefault);//更新fact中变量值
                        update(ai_agent_contextbindai_agent_assignment);//更新fact中变量值
            end