package cn.ibizlab.ai.logic.ai_agent_contextlogic.chat_analyze_documents;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextchat_analyze_documentsdefault;
                global java.util.Map ai_agent_contextchat_analyze_documentsintentlist;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextchat_analyze_documentsbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_agent_contextchat_analyze_documentsprepareparam_01"
            when
            then
                            ai_agent_contextchat_analyze_documentsdefault.set("knowledgebases","efe2de90-ef60-4b13-6529-f8ddef4c9efe");
                            ai_agent_contextchat_analyze_documentsdefault.set("chunkqueries",ai_agent_contextchat_analyze_documentsintentlist.get(""));
                        update(ai_agent_contextchat_analyze_documentsdefault);//更新fact中变量值
                        update(ai_agent_contextchat_analyze_documentsintentlist);//更新fact中变量值
            end

            //逻辑处理节点[交谈执行代码输出文档]
            rule "sysaichatagent_chatexecutecode_documents_01"
            ruleflow-group "ai_agent_contextchat_analyze_documentssysaichatagent_chatexecutecode_documents_01"
            when
            then
                        update(ai_agent_contextchat_analyze_documentsdefault);//更新fact中变量值
                        update(ai_agent_contextchat_analyze_documentsintentlist);//更新fact中变量值
            end

            //逻辑处理节点[意图整理]
            rule "sysaichatagent_chatintents_01"
            ruleflow-group "ai_agent_contextchat_analyze_documentssysaichatagent_chatintents_01"
            when
            then
                        update(ai_agent_contextchat_analyze_documentsdefault);//更新fact中变量值
                        update(ai_agent_contextchat_analyze_documentsintentlist);//更新fact中变量值
            end