package cn.ibizlab.ai.logic.ai_agent_contextlogic.chat_execute_action;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextchat_execute_actiondefault;
                    global cn.ibizlab.core.ai.service.Iai_agent_contextService ai_agent_contextservice;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextchat_execute_actionbegin"
            when
            then
            end

            //逻辑处理节点[等待输入]
            rule "sysaichatagent_chatinput_01"
            ruleflow-group "ai_agent_contextchat_execute_actionsysaichatagent_chatinput_01"
            when
            then
                        update(ai_agent_contextchat_execute_actiondefault);//更新fact中变量值
            end

            //逻辑处理节点[交谈执行行为]
            rule "sysaichatagent_chatexecuteaction_01"
            ruleflow-group "ai_agent_contextchat_execute_actionsysaichatagent_chatexecuteaction_01"
            when
            then
                        update(ai_agent_contextchat_execute_actiondefault);//更新fact中变量值
            end