package cn.ibizlab.ai.logic.ai_agent_contextlogic.chat_execute_skill;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextchat_execute_skilldefault;
                global java.util.Map ai_agent_contextchat_execute_skillintentlist;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextchat_execute_skillbegin"
            when
            then
            end

            //逻辑处理节点[意图整理]
            rule "sysaichatagent_chatintents_01"
            ruleflow-group "ai_agent_contextchat_execute_skillsysaichatagent_chatintents_01"
            when
            then
                        update(ai_agent_contextchat_execute_skilldefault);//更新fact中变量值
                        update(ai_agent_contextchat_execute_skillintentlist);//更新fact中变量值
            end

            //逻辑处理节点[交谈执行技能]
            rule "sysaichatagent_chatexecuteskill_01"
            ruleflow-group "ai_agent_contextchat_execute_skillsysaichatagent_chatexecuteskill_01"
            when
            then
                        update(ai_agent_contextchat_execute_skilldefault);//更新fact中变量值
                        update(ai_agent_contextchat_execute_skillintentlist);//更新fact中变量值
            end