package cn.ibizlab.ai.logic.ai_agent_contextlogic.get_by_code;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_agent_context ai_agent_contextget_by_codedefault;
                    global cn.ibizlab.core.ai.service.Iai_agent_contextService ai_agent_contextservice;
        global cn.ibizlab.core.ai.service.Iai_agent_contextService iBzSysAi_agent_contextDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_agent_contextget_by_codebegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall_01"
            ruleflow-group "ai_agent_contextget_by_coderawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_agent_contextget_by_codedefault.get("codename"));
        param.put("param1",ai_agent_contextget_by_codedefault.get("codename"));
    String strSql="select max(id) as id from ai_agent_context where code_name=#{et.param0} or code_name like concat(#{et.param1},'@%')";
                        java.util.List<JSONObject> entities=iBzSysAi_agent_contextDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    cn.ibizlab.core.ai.domain.ai_agent_context targetEntity =new cn.ibizlab.core.ai.domain.ai_agent_context();
                                    for (Map.Entry entry : entity.entrySet()) {
                                    targetEntity.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                                    org.springframework.cglib.beans.BeanCopier copier= org.springframework.cglib.beans.BeanCopier.create(targetEntity.getClass(),ai_agent_contextget_by_codedefault.getClass(), false);
                                    copier.copy(targetEntity,ai_agent_contextget_by_codedefault,null);
                            }
                        update(ai_agent_contextget_by_codedefault);//更新fact中变量值
            end

            //逻辑处理节点[实体行为]
            rule "deaction_01"
            ruleflow-group "ai_agent_contextget_by_codedeaction_01"
            when
            then
                            cn.ibizlab.util.helper.CachedBeanCopier.copy(ai_agent_contextservice.get(ai_agent_contextget_by_codedefault.getId()),ai_agent_contextget_by_codedefault);
                        update(ai_agent_contextget_by_codedefault);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "ai_agent_contextget_by_coderawsfcode_01"
            when
            then
                        update(ai_agent_contextget_by_codedefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_agent_contextget_by_codeend_01"
            when
            then
                        update(ai_agent_contextget_by_codedefault);//更新fact中变量值
            end