package cn.ibizlab.ai.logic.ai_knowledge_baselogic.create_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_basecreate_memberdefault;
                global cn.ibizlab.core.ai.domain.ai_kb_member ai_knowledge_basecreate_memberai_kb_member;
                    global cn.ibizlab.core.ai.service.Iai_kb_memberService ai_kb_memberservice;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_basecreate_memberbegin"
            when
            then
            end

            //逻辑处理节点[设置成员信息]
            rule "prepareparam_01"
            ruleflow-group "ai_knowledge_basecreate_memberprepareparam_01"
            when
            then
                            ai_knowledge_basecreate_memberai_kb_member.set("kbid",ai_knowledge_basecreate_memberdefault.get("id"));
                                ai_knowledge_basecreate_memberai_kb_member.set("userid",curuser.getSessionParams().get("srfuserid"));
                            ai_knowledge_basecreate_memberai_kb_member.set("roleid","admin");
                        update(ai_knowledge_basecreate_memberdefault);//更新fact中变量值
                        update(ai_knowledge_basecreate_memberai_kb_member);//更新fact中变量值
            end

            //逻辑处理节点[创建默认成员]
            rule "deaction_01"
            ruleflow-group "ai_knowledge_basecreate_memberdeaction_01"
            when
            then
                        ai_kb_memberservice.create(ai_knowledge_basecreate_memberai_kb_member);
                        update(ai_knowledge_basecreate_memberdefault);//更新fact中变量值
                        update(ai_knowledge_basecreate_memberai_kb_member);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_knowledge_basecreate_memberend_01"
            when
            then
                        update(ai_knowledge_basecreate_memberdefault);//更新fact中变量值
                        update(ai_knowledge_basecreate_memberai_kb_member);//更新fact中变量值
            end