package cn.ibizlab.ai.logic.ai_knowledge_baselogic.favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_basefavoritedefault;
                global cn.ibizlab.core.base.domain.favorite ai_knowledge_basefavoritefavorite;
                    global cn.ibizlab.core.base.service.IfavoriteService favoriteservice;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_basefavoritebegin"
            when
            then
            end

            //逻辑处理节点[填充用户标识和收藏业务对象标识]
            rule "prepareparam1"
            ruleflow-group "ai_knowledge_basefavoriteprepareparam1"
            when
            then
                                ai_knowledge_basefavoritefavorite.set("createman",curuser.getSessionParams().get("srfuserid"));
                            ai_knowledge_basefavoritefavorite.set("ownertype","ai_knowledge_base");
                            ai_knowledge_basefavoritefavorite.set("ownerid",ai_knowledge_basefavoritedefault.get("owner_id"));
                        update(ai_knowledge_basefavoritedefault);//更新fact中变量值
                        update(ai_knowledge_basefavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[生成收藏数据]
            rule "deaction1"
            ruleflow-group "ai_knowledge_basefavoritedeaction1"
            when
            then
                        favoriteservice.save(ai_knowledge_basefavoritefavorite);
                        update(ai_knowledge_basefavoritedefault);//更新fact中变量值
                        update(ai_knowledge_basefavoritefavorite);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ai_knowledge_basefavoriteend1"
            when
            then
                        update(ai_knowledge_basefavoritedefault);//更新fact中变量值
                        update(ai_knowledge_basefavoritefavorite);//更新fact中变量值
            end