package cn.ibizlab.ai.logic.ai_knowledge_baselogic.keywords;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_basekeywordsdefault;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_basekeywordsbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_knowledge_basekeywordsend_01"
            when
            then
                        update(ai_knowledge_basekeywordsdefault);//更新fact中变量值
            end

            //逻辑处理节点[解析keywords]
            rule "rawsfcode_01"
            ruleflow-group "ai_knowledge_basekeywordsrawsfcode_01"
            when
            then
                        update(ai_knowledge_basekeywordsdefault);//更新fact中变量值
            end