package cn.ibizlab.ai.logic.ai_knowledge_baselogic.ls;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_baselsdefault;
                global cn.ibizlab.core.ai.domain.ai_kb_document ai_knowledge_baselsdocfilter;
                global cn.ibizlab.core.ai.domain.ai_kb_document ai_knowledge_baselsdoclist;
                global java.util.Map ai_knowledge_baselsresultjson;
                    global cn.ibizlab.core.ai.service.Iai_kb_documentService ai_kb_documentservice;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_baselsbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_knowledge_baselsprepareparam_01"
            when
            then
                            ai_knowledge_baselsdocfilter.set("kbid",ai_knowledge_baselsdefault.get("id"));
                            ai_knowledge_baselsdocfilter.set("size","150");
                            ai_knowledge_baselsdocfilter.set("sort","sequence,asc");
                        update(ai_knowledge_baselsdefault);//更新fact中变量值
                        update(ai_knowledge_baselsdocfilter);//更新fact中变量值
                        update(ai_knowledge_baselsdoclist);//更新fact中变量值
                        update(ai_knowledge_baselsresultjson);//更新fact中变量值
            end

            //逻辑处理节点[实体数据查询]
            rule "dedataquery_01"
            ruleflow-group "ai_knowledge_baselsdedataquery_01"
            when
            then
                        update(ai_knowledge_baselsdefault);//更新fact中变量值
                        update(ai_knowledge_baselsdocfilter);//更新fact中变量值
                        update(ai_knowledge_baselsdoclist);//更新fact中变量值
                        update(ai_knowledge_baselsresultjson);//更新fact中变量值
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "ai_knowledge_baselsrawsfcode_01"
            when
            then
                        update(ai_knowledge_baselsdefault);//更新fact中变量值
                        update(ai_knowledge_baselsdocfilter);//更新fact中变量值
                        update(ai_knowledge_baselsdoclist);//更新fact中变量值
                        update(ai_knowledge_baselsresultjson);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_knowledge_baselsend_01"
            when
            then
                        update(ai_knowledge_baselsdefault);//更新fact中变量值
                        update(ai_knowledge_baselsdocfilter);//更新fact中变量值
                        update(ai_knowledge_baselsdoclist);//更新fact中变量值
                        update(ai_knowledge_baselsresultjson);//更新fact中变量值
            end