package cn.ibizlab.ai.logic.ai_knowledge_baselogic.reset_all_chunk;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_basereset_all_chunkdefault;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_basereset_all_chunkbegin"
            when
            then
            end

            //逻辑处理节点[直接sql调用]
            rule "rawsqlcall_01"
            ruleflow-group "ai_knowledge_basereset_all_chunkrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_knowledge_basereset_all_chunkdefault.get("id"));
        param.put("param1",ai_knowledge_basereset_all_chunkdefault.get("id"));
        param.put("param2",ai_knowledge_basereset_all_chunkdefault.get("id"));
        param.put("param3",ai_knowledge_basereset_all_chunkdefault.get("id"));
        param.put("param4",ai_knowledge_basereset_all_chunkdefault.get("id"));
        param.put("param5",ai_knowledge_basereset_all_chunkdefault.get("id"));
    String strSql="delete from ai_kb_chunk where document_id in (select id from ai_kb_document where kb_id=#{et.param0}) ; delete from ai_kb_graph_entity_chunk where ai_kb_graph_entity_chunk.entity_id in (select id from ai_kb_graph_entity where kb_id=#{et.param1}) ; delete from ai_kb_graph_entity where  kb_id=#{et.param2} ; delete from ai_kb_graph_relation_chunk where ai_kb_graph_relation_chunk.relation_id in (select id from ai_kb_graph_relation where kb_id=#{et.param3}) ; delete from ai_kb_graph_relation where   kb_id=#{et.param4}  ; update ai_kb_document set chunk_method=(select chunk_method from ai_knowledge_base where ai_knowledge_base.id=ai_kb_document.kb_id),status='3',parsed_content = null where kb_id = '785219b0c35d9739f271d5cba07df681'; ";
                        iBzSysAi_knowledge_baseDefaultService.execute(strSql,param);//SQL调用
                        update(ai_knowledge_basereset_all_chunkdefault);//更新fact中变量值
            end