package cn.ibizlab.ai.logic.ai_knowledge_baselogic.un_favorite;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_baseun_favoritedefault;
                global cn.ibizlab.core.ai.domain.ai_knowledge_base ai_knowledge_baseun_favoriteupdateobj;
        global cn.ibizlab.core.ai.service.Iai_knowledge_baseService iBzSysAi_knowledge_baseDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_knowledge_baseun_favoritebegin"
            when
            then
            end

            //逻辑处理节点[删除收藏数据]
            rule "rawsqlcall1"
            ruleflow-group "ai_knowledge_baseun_favoriterawsqlcall1"
            when
            then
    Map param =new HashMap();
        param.put("param0",curuser.getSessionParams().get("srfuserid"));
        param.put("param1",ai_knowledge_baseun_favoritedefault.get("owner_id"));
    String strSql="delete from favorite where create_man = #{et.param0} and owner_id = #{et.param1}";
                        iBzSysAi_knowledge_baseDefaultService.execute(strSql,param);//SQL调用
                        update(ai_knowledge_baseun_favoritedefault);//更新fact中变量值
                        update(ai_knowledge_baseun_favoriteupdateobj);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end1"
            ruleflow-group "ai_knowledge_baseun_favoriteend1"
            when
            then
                        update(ai_knowledge_baseun_favoritedefault);//更新fact中变量值
                        update(ai_knowledge_baseun_favoriteupdateobj);//更新fact中变量值
            end