package cn.ibizlab.base.logic.portfolio_memberlogic.remove_project_set_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.portfolio_member portfolio_memberremove_project_set_member_notifydefault;
        global cn.ibizlab.core.base.service.Iportfolio_memberService iBzSysPortfolio_memberDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolio_memberremove_project_set_member_notifybegin"
            when
            then
            end