package cn.ibizlab.base.logic.portfoliologic.portfolio_addon_authority;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.portfolio portfolioportfolio_addon_authoritydefault;
                global cn.ibizlab.core.base.domain.portfolio portfolioportfolio_addon_authorityresult;
        global cn.ibizlab.core.base.service.IportfolioService iBzSysPortfolioDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "portfolioportfolio_addon_authoritybegin"
            when
            then
            end