package cn.ibizlab.ai.logic.ai_toollogic.get_skill_runner_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_tool ai_toolget_skill_runner_infodefault;
        global cn.ibizlab.core.ai.service.Iai_toolService iBzSysAi_toolDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_toolget_skill_runner_infobegin"
            when
            then
            end

            //逻辑处理节点[获取runner配置]
            rule "rawsfcode_01"
            ruleflow-group "ai_toolget_skill_runner_inforawsfcode_01"
            when
            then
                        update(ai_toolget_skill_runner_infodefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_toolget_skill_runner_infoend_01"
            when
            then
                        update(ai_toolget_skill_runner_infodefault);//更新fact中变量值
            end