package cn.ibizlab.ai.logic.ai_credentiallogic.findmycredential;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global java.util.Map ai_credentialfindmycredentialdefault;
                global cn.ibizlab.core.ai.domain.ai_credential ai_credentialfindmycredentialresult;
        global cn.ibizlab.core.ai.service.Iai_credentialService iBzSysAi_credentialDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_credentialfindmycredentialbegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "ai_credentialfindmycredentialprepareparam_01"
            when
            then
                            ai_credentialfindmycredentialresult.set("provider",ai_credentialfindmycredentialdefault.get("provider"));
                        update(ai_credentialfindmycredentialdefault);//更新fact中变量值
                        update(ai_credentialfindmycredentialresult);//更新fact中变量值
            end

            //逻辑处理节点[查询凭证]
            rule "rawsfcode_01"
            ruleflow-group "ai_credentialfindmycredentialrawsfcode_01"
            when
            then
                        update(ai_credentialfindmycredentialdefault);//更新fact中变量值
                        update(ai_credentialfindmycredentialresult);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_credentialfindmycredentialend_01"
            when
            then
                        update(ai_credentialfindmycredentialdefault);//更新fact中变量值
                        update(ai_credentialfindmycredentialresult);//更新fact中变量值
            end