package cn.ibizlab.base.logic.memberlogic.choose_project_resource;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.member memberchoose_project_resourcedefault;
                global cn.ibizlab.core.base.domain.member memberchoose_project_resourcefor_member;
                global cn.ibizlab.core.base.domain.user memberchoose_project_resourcefor_user_obj;
                global cn.ibizlab.core.base.domain.member memberchoose_project_resourcegroup_page;
                global cn.ibizlab.core.base.domain.user memberchoose_project_resourceuser_filter;
                global cn.ibizlab.core.base.domain.user memberchoose_project_resourceuser_page;
        global cn.ibizlab.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "memberchoose_project_resourcebegin"
            when
            then
            end