package cn.ibizlab.base.logic.memberlogic.resource_member;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.member memberresource_memberdefault;
                global cn.ibizlab.core.base.domain.member memberresource_membermember_list;
                global cn.ibizlab.core.base.domain.member memberresource_membermember_page;
        global cn.ibizlab.core.base.service.ImemberService iBzSysMemberDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "memberresource_memberbegin"
            when
            then
            end