package cn.ibizlab.base.logic.extend_loglogic.last_exec_time;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.extend_log extend_loglast_exec_timedefault;
                global cn.ibizlab.core.base.domain.extend_log extend_loglast_exec_timelast_extend_log;
                global cn.ibizlab.core.base.domain.extend_log extend_loglast_exec_timelog_filter;
                global cn.ibizlab.core.base.domain.extend_log extend_loglast_exec_timelog_page;
                    global cn.ibizlab.core.base.service.Iextend_logService extend_logservice;
        global cn.ibizlab.core.base.service.Iextend_logService iBzSysExtend_logDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "extend_loglast_exec_timebegin"
            when
            then
            end

            //逻辑处理节点[准备参数]
            rule "prepareparam_01"
            ruleflow-group "extend_loglast_exec_timeprepareparam_01"
            when
            then
                            extend_loglast_exec_timelog_filter.set("n_owner_id_eq",extend_loglast_exec_timedefault.get("ownerid"));
                            extend_loglast_exec_timelog_filter.set("n_state_eq","SUCCESS");
                            extend_loglast_exec_timelog_filter.set("n_owner_subtype_eq","PSDELOGIC");
                            extend_loglast_exec_timelog_filter.set("sort","end_at,desc");
                            extend_loglast_exec_timelog_filter.set("size","1");
                        update(extend_loglast_exec_timedefault);//更新fact中变量值
                        update(extend_loglast_exec_timelast_extend_log);//更新fact中变量值
                        update(extend_loglast_exec_timelog_filter);//更新fact中变量值
                        update(extend_loglast_exec_timelog_page);//更新fact中变量值
            end

            //逻辑处理节点[查询记录]
            rule "dedataquery_01"
            ruleflow-group "extend_loglast_exec_timededataquery_01"
            when
            then
                        update(extend_loglast_exec_timedefault);//更新fact中变量值
                        update(extend_loglast_exec_timelast_extend_log);//更新fact中变量值
                        update(extend_loglast_exec_timelog_filter);//更新fact中变量值
                        update(extend_loglast_exec_timelog_page);//更新fact中变量值
            end

            //逻辑处理节点[绑定参数]
            rule "bindparam_01"
            ruleflow-group "extend_loglast_exec_timebindparam_01"
            when
            then
                        update(extend_loglast_exec_timedefault);//更新fact中变量值
                        update(extend_loglast_exec_timelast_extend_log);//更新fact中变量值
                        update(extend_loglast_exec_timelog_filter);//更新fact中变量值
                        update(extend_loglast_exec_timelog_page);//更新fact中变量值
            end

            //逻辑处理节点[赋值最后一次成功执行时间]
            rule "prepareparam_02"
            ruleflow-group "extend_loglast_exec_timeprepareparam_02"
            when
            then
                            extend_loglast_exec_timedefault.set("last_exec_time",extend_loglast_exec_timelast_extend_log.get("endat"));
                        update(extend_loglast_exec_timedefault);//更新fact中变量值
                        update(extend_loglast_exec_timelast_extend_log);//更新fact中变量值
                        update(extend_loglast_exec_timelog_filter);//更新fact中变量值
                        update(extend_loglast_exec_timelog_page);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "extend_loglast_exec_timeend_01"
            when
            then
                        update(extend_loglast_exec_timedefault);//更新fact中变量值
                        update(extend_loglast_exec_timelast_extend_log);//更新fact中变量值
                        update(extend_loglast_exec_timelog_filter);//更新fact中变量值
                        update(extend_loglast_exec_timelog_page);//更新fact中变量值
            end