package cn.ibizlab.ai.logic.ai_kb_documentlogic.ai_kb_document_type_counters;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_kb_document ai_kb_documentai_kb_document_type_countersdefault;
        global cn.ibizlab.core.ai.service.Iai_kb_documentService iBzSysAi_kb_documentDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_documentai_kb_document_type_countersbegin"
            when
            then
            end

            //逻辑处理节点[统计知识库分类数量]
            rule "rawsqlcall_01"
            ruleflow-group "ai_kb_documentai_kb_document_type_countersrawsqlcall_01"
            when
            then
    Map param =new HashMap();
        param.put("param0",ai_kb_documentai_kb_document_type_countersdefault.get("kbid"));
    String strSql="SELECT COUNT(*) AS total FROM ai_kb_document WHERE kb_id = #{et.param0}";
                        java.util.List<JSONObject> entities=iBzSysAi_kb_documentDefaultService.select(strSql,param);//SQL调用
                            if(entities.size()>0){
                            JSONObject entity=entities.get(0);
                                    for (Map.Entry entry : entity.entrySet()) {
                                    ai_kb_documentai_kb_document_type_countersdefault.set(String.valueOf(entry.getKey()),entry.getValue());
                                    }
                            }
                        update(ai_kb_documentai_kb_document_type_countersdefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_documentai_kb_document_type_countersend_01"
            when
            then
                        update(ai_kb_documentai_kb_document_type_countersdefault);//更新fact中变量值
            end