package cn.ibizlab.base.logic.rolelogic.cursystem;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.base.domain.role rolecursystemdefault;
                global cn.ibizlab.core.base.domain.role rolecursystemfilteredroles;
                global cn.ibizlab.core.base.domain.role rolecursystemresultpage;
                global java.util.Map rolecursystemsysarg;
                    global cn.ibizlab.core.base.service.IroleService roleservice;
        global cn.ibizlab.core.base.service.IroleService iBzSysRoleDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "rolecursystembegin"
            when
            then
            end

            //逻辑处理节点[准备过滤器参数]
            rule "prepareparam"
            ruleflow-group "rolecursystemprepareparam"
            when
            then
                                rolecursystemsysarg.set("dcsystemid",curuser.getSessionParams().get("srfdcsystemid"));
                            rolecursystemdefault.set("size","1000");
                        update(rolecursystemdefault);//更新fact中变量值
                        update(rolecursystemfilteredroles);//更新fact中变量值
                        update(rolecursystemresultpage);//更新fact中变量值
                        update(rolecursystemsysarg);//更新fact中变量值
            end

            //逻辑处理节点[调试逻辑参数]
            rule "debugparam_01"
            ruleflow-group "rolecursystemdebugparam_01"
            when
            then
                        update(rolecursystemdefault);//更新fact中变量值
                        update(rolecursystemfilteredroles);//更新fact中变量值
                        update(rolecursystemresultpage);//更新fact中变量值
                        update(rolecursystemsysarg);//更新fact中变量值
            end

            //逻辑处理节点[实体数据集]
            rule "dedataset_01"
            ruleflow-group "rolecursystemdedataset_01"
            when
            then
                        update(rolecursystemdefault);//更新fact中变量值
                        update(rolecursystemfilteredroles);//更新fact中变量值
                        update(rolecursystemresultpage);//更新fact中变量值
                        update(rolecursystemsysarg);//更新fact中变量值
            end

            //逻辑处理节点[过滤角色数据]
            rule "rawsfcode"
            ruleflow-group "rolecursystemrawsfcode"
            when
            then
                        update(rolecursystemdefault);//更新fact中变量值
                        update(rolecursystemfilteredroles);//更新fact中变量值
                        update(rolecursystemresultpage);//更新fact中变量值
                        update(rolecursystemsysarg);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end"
            ruleflow-group "rolecursystemend"
            when
            then
                        update(rolecursystemdefault);//更新fact中变量值
                        update(rolecursystemfilteredroles);//更新fact中变量值
                        update(rolecursystemresultpage);//更新fact中变量值
                        update(rolecursystemsysarg);//更新fact中变量值
            end