package cn.ibizlab.extension.logic.psdelogiclogic.publishconfig;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.extension.domain.PSDELogic psdelogicpublishconfigdefault;
                    global cn.ibizlab.core.extension.service.IPSDELogicService psdelogicservice;
        global cn.ibizlab.core.extension.service.IPSDELogicService iBzSysPsdelogicDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "psdelogicpublishconfigbegin"
            when
            then
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "psdelogicpublishconfigend_01"
            when
            then
                        update(psdelogicpublishconfigdefault);//更新fact中变量值
            end

            //逻辑处理节点[获取逻辑数据]
            rule "deaction_01"
            ruleflow-group "psdelogicpublishconfigdeaction_01"
            when
            then
                            cn.ibizlab.util.helper.CachedBeanCopier.copy(psdelogicservice.get(psdelogicpublishconfigdefault.getPsdelogicid()),psdelogicpublishconfigdefault);
                        update(psdelogicpublishconfigdefault);//更新fact中变量值
            end

            //逻辑处理节点[发布配置]
            rule "rawsfcode_01"
            ruleflow-group "psdelogicpublishconfigrawsfcode_01"
            when
            then
                        update(psdelogicpublishconfigdefault);//更新fact中变量值
            end