package cn.ibizlab.wiki.logic.space_memberlogic.remove_space_member_notify;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.wiki.domain.space_member space_memberremove_space_member_notifydefault;
        global cn.ibizlab.core.wiki.service.Ispace_memberService iBzSysSpace_memberDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "space_memberremove_space_member_notifybegin"
            when
            then
            end