package cn.ibizlab.ai.logic.ai_kb_chunklogic.get_page_index_info;
        import java.util.Map;
        import java.util.HashMap;
        import com.alibaba.fastjson.JSONObject;
        import org.springframework.util.StringUtils;
        import org.springframework.util.ObjectUtils;
        import cn.ibizlab.util.errors.BadRequestAlertException;
                global cn.ibizlab.core.ai.domain.ai_kb_chunk ai_kb_chunkget_page_index_infodefault;
        global cn.ibizlab.core.ai.service.Iai_kb_chunkService iBzSysAi_kb_chunkDefaultService;
        global cn.ibizlab.util.security.AuthenticationUser curuser;


    no-loop

            //逻辑处理节点[开始]
            rule "begin"
            ruleflow-group "ai_kb_chunkget_page_index_infobegin"
            when
            then
            end

            //逻辑处理节点[执行脚本代码]
            rule "rawsfcode_01"
            ruleflow-group "ai_kb_chunkget_page_index_inforawsfcode_01"
            when
            then
                        update(ai_kb_chunkget_page_index_infodefault);//更新fact中变量值
            end

            //逻辑处理节点[结束]
            rule "end_01"
            ruleflow-group "ai_kb_chunkget_page_index_infoend_01"
            when
            then
                        update(ai_kb_chunkget_page_index_infodefault);//更新fact中变量值
            end